### ISSUE TITLE
MOODLE_INTERNAL check

### ISSUE THREAD

**Issue by OlenaTatarintseva** [dualcube/moodle-enrol_stripepayment#32]
Hello,

First of all I want say thank you for your work with the plugin.

I just would like to suggest, that it would be good to add MOODLE_INTERNAL check in php files in enrol/stripepayment/Stripe/lib/Stripe according to https://docs.moodle.org/dev/Coding_style#Require_.2F_include.

Best regards,
Olena Tatarintseva

**Comment by trideepdm** [comment]
Dear Olena,
Thanks for your suggestions. 
We are already added MOODLE_INTERNAL check in all of the php files excluding the stripe sdk one's. It would be hard to maintain the plugin if we implement any change in the php files of the stripe sdk because we update this whenever stripe publishes new version for this stripe sdk.

Thank you.

**Comment by OlenaTatarintseva** [comment]
OK, thank you for your response.
